[project]
name = "spark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightning",
    "pandas",
    "pyarrow",
    "torch",
    "wandb",
    "loguru",
    "h5py",
]

[dependency-groups]
dev = [
    "huggingface-hub",
    "ipykernel",
    "jupyter",
    "jupyterlab",
    "matplotlib",
    "seaborn",
]
